name: Type-checking with Pyright

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyright
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Type-check with Pyright
      run: |
        pyright --warnings
